/**
 * PETMOL Recommendations — editorial picks with official Amazon Associates US
 * Special Links.
 *
 * HARD RULES (see the mission brief):
 *  - `affiliateUrl` is the EXACT amzn.to Special Link generated by the
 *    Amazon SiteStripe on the PETMOL Associates account. It is NEVER rebuilt,
 *    never gets a manual `?tag=`, never runs through `features/commerce/amazon.ts`
 *    (that module is for amazon.com.br and is unrelated to this page), and is
 *    never wrapped in an internal redirect. The public `href` IS this string.
 *  - No prices, ratings, review counts, stock, shipping or "best price" claims.
 *  - No Amazon images, no scraping, no Product Advertising API.
 *  - Products whose destination could not be identified with confidence are
 *    kept here, flagged `needsEditorialMetadata`, and reported for a human to
 *    fill in. Their title/blurb are deliberately generic — nothing invented.
 *
 * Store / Tracking ID on the account: petmol07-20 (embedded by Amazon inside
 * each Special Link — do not touch).
 */

export type RecommendationCategory =
  | 'for-pets'
  | 'home-with-pets'
  | 'cleaning-organization'
  | 'smart-home-technology'
  | 'travel-outdoors'
  | 'petmol-finds';

export interface RecommendationCategoryMeta {
  id: RecommendationCategory;
  label: string;
  description: string;
}

export const RECOMMENDATION_CATEGORIES: RecommendationCategoryMeta[] = [
  {
    id: 'for-pets',
    label: 'For Pets',
    description: 'Everyday gear that makes life a little easier for the animal itself.',
  },
  {
    id: 'home-with-pets',
    label: 'Home with Pets',
    description: 'Things that help a home and an animal share the same space.',
  },
  {
    id: 'cleaning-organization',
    label: 'Cleaning & Organization',
    description: 'For the fur, the spills and the general chaos that comes with pets.',
  },
  {
    id: 'smart-home-technology',
    label: 'Smart Home & Technology',
    description: 'Small pieces of technology we find genuinely useful at home.',
  },
  {
    id: 'travel-outdoors',
    label: 'Travel & Outdoors',
    description: 'For trips, walks and being away from home with a pet.',
  },
  {
    id: 'petmol-finds',
    label: 'PETMOL Finds',
    description: 'A catch-all for interesting things we run into — not always pet-related.',
  },
];

export interface Recommendation {
  id: string;
  /** Editorial title. For identified picks it names the product line the
   *  client's own Special Link points to. Never an invented brand or model. */
  title: string;
  /** Short, original PETMOL editorial note — why it might be useful. Never
   *  copied from Amazon. */
  blurb: string;
  category: RecommendationCategory;
  /** EXACT amzn.to Special Link from the Amazon SiteStripe. Rendered verbatim. */
  affiliateUrl: string;
  /** true = we could not confidently identify the destination product; a human
   *  must confirm the title/description. The link is still real and rendered. */
  needsEditorialMetadata?: boolean;
}

/**
 * The 11 official Special Links received from the PETMOL Amazon Associates
 * account, in the order they were provided.
 *
 * Destinations were resolved only by following each short link's HTTP
 * redirect (the `Location` header) — no product page was fetched. Links whose
 * redirect target is a bare `/dp/<ASIN>` with no readable product hint are
 * flagged below; links whose target is an Amazon search (`?k=<terms>`) name
 * the product the client chose to point at.
 */
export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'rec-01',
    title: 'A PETMOL find (being written up)',
    blurb:
      'One of our picks — we are still confirming the exact product before writing a proper note about it.',
    category: 'petmol-finds',
    affiliateUrl: 'https://amzn.to/3Uzcsf4',
    needsEditorialMetadata: true,
  },
  {
    id: 'rec-02',
    title: 'Wyze Smart Plug',
    blurb:
      'A small plug that puts a lamp, a fan or an aquarium pump on a schedule from your phone. Handy for keeping a routine while you are out.',
    category: 'smart-home-technology',
    affiliateUrl: 'https://amzn.to/3SmPhUL',
  },
  {
    id: 'rec-03',
    title: 'Another PETMOL find (being written up)',
    blurb:
      'A second pick we like but have not finished identifying — we will not describe a product we are not sure about.',
    category: 'petmol-finds',
    affiliateUrl: 'https://amzn.to/4gGI8qi',
    needsEditorialMetadata: true,
  },
  {
    id: 'rec-04',
    title: 'Wyze Security Camera',
    blurb:
      'An inexpensive indoor camera. People often use one to check in on a pet that stays home alone during the day.',
    category: 'smart-home-technology',
    affiliateUrl: 'https://amzn.to/4cXWj9l',
  },
  {
    id: 'rec-05',
    title: 'Furbo Dog Camera',
    blurb:
      'An indoor pet camera that can toss a treat and send a phone alert when it hears barking — made specifically for watching dogs while you are away.',
    category: 'smart-home-technology',
    affiliateUrl: 'https://amzn.to/4x6HXuG',
  },
  {
    id: 'rec-06',
    title: 'Pet Water Fountain',
    blurb:
      'A circulating water bowl. Moving water gets some pets — cats especially — to drink more than they would from a still bowl.',
    category: 'for-pets',
    affiliateUrl: 'https://amzn.to/4cplcKW',
  },
  {
    id: 'rec-07',
    title: 'ChomChom Roller',
    blurb:
      'A reusable pet-hair remover for sofas, beds and car seats. No sticky sheets to run out of — you empty a little chamber and reuse it.',
    category: 'cleaning-organization',
    affiliateUrl: 'https://amzn.to/4qR9sqC',
  },
  {
    id: 'rec-08',
    title: 'A PETMOL find (being written up)',
    blurb:
      'A pick we have not finished identifying. We are keeping the link here and will add a real note once a person confirms the product.',
    category: 'petmol-finds',
    affiliateUrl: 'https://amzn.to/4yge3VH',
    needsEditorialMetadata: true,
  },
  {
    id: 'rec-09',
    title: 'KONG Classic Dog Toy',
    blurb:
      'The classic hollow rubber chew you can stuff with food. A simple way to keep a dog busy for a while, and it survives most chewers.',
    category: 'for-pets',
    affiliateUrl: 'https://amzn.to/4gwMD8b',
  },
  {
    id: 'rec-10',
    title: 'BISSELL Little Green Pet',
    blurb:
      'A small portable carpet and upholstery cleaner. The size people reach for when a pet has an accident on a rug or the couch.',
    category: 'cleaning-organization',
    affiliateUrl: 'https://amzn.to/46zcuWZ',
  },
  {
    id: 'rec-11',
    title: 'AirTag Pet Collar Holder',
    blurb:
      'A holder that clips an Apple AirTag onto a collar. Not a GPS tracker — it helps you find a pet that is nearby, or that someone else has found.',
    category: 'travel-outdoors',
    affiliateUrl: 'https://amzn.to/4qV30Pu',
  },
];

/** Categories that actually have at least one pick, in display order. */
export function getPopulatedCategories(): RecommendationCategoryMeta[] {
  return RECOMMENDATION_CATEGORIES.filter((c) =>
    RECOMMENDATIONS.some((r) => r.category === c.id),
  );
}

export function getRecommendationsByCategory(category: RecommendationCategory): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.category === category);
}

/** Links that still need a human to confirm the product. */
export function getRecommendationsNeedingMetadata(): Recommendation[] {
  return RECOMMENDATIONS.filter((r) => r.needsEditorialMetadata);
}

// ── Disclosure text (English) ──────────────────────────────────────────────

/** The exact statement the Amazon Associates Operating Agreement requires. */
export const AMAZON_REQUIRED_STATEMENT =
  'As an Amazon Associate I earn from qualifying purchases.';

export const RECOMMENDATIONS_DISCLOSURE_SHORT =
  'The links below are affiliate (paid) links. If you buy through one, PETMOL may earn a commission on qualifying purchases, at no extra cost to you.';

export const RECOMMENDATIONS_INTRO =
  'This is a running list of products PETMOL finds interesting or genuinely useful — for pets, for the people who care for them, for the home, and sometimes for everyday life in general. It is not a store: PETMOL does not sell, stock, price or ship anything. Every purchase happens on Amazon, under Amazon’s own terms.';
